#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-hdf5-soname10
Version  : 1.8.20
Release  : 4
URL      : https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.20.tar.gz
Source0  : https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.20.tar.gz
Summary  : HDF5 is a unique technology suite that makes possible the management of extremely large and complex data collections.
Group    : Development/Tools
License  : BSD-4-Clause-UC
Requires: compat-hdf5-soname10-lib = %{version}-%{release}
Requires: compat-hdf5-soname10-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : pkgconfig(zlib)

%description
This distribution contains the HDF5 FORTRAN90 APIs source code (prototype)
based on the HDF5 1.2.2 release (ftp://ftp.ncsa.uiuc.edu/HDF/HDF5/current),
tests and examples.

%package lib
Summary: lib components for the compat-hdf5-soname10 package.
Group: Libraries
Requires: compat-hdf5-soname10-license = %{version}-%{release}

%description lib
lib components for the compat-hdf5-soname10 package.


%package license
Summary: license components for the compat-hdf5-soname10 package.
Group: Default

%description license
license components for the compat-hdf5-soname10 package.


%prep
%setup -q -n hdf5-1.8.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1564681927
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1564681927
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-hdf5-soname10
cp COPYING %{buildroot}/usr/share/package-licenses/compat-hdf5-soname10/COPYING
%make_install
## Remove excluded files
rm -f %{buildroot}/usr/lib64/libhdf5.settings
rm -f %{buildroot}/usr/bin/gif2h5
rm -f %{buildroot}/usr/bin/h52gif
rm -f %{buildroot}/usr/bin/h5cc
rm -f %{buildroot}/usr/bin/h5copy
rm -f %{buildroot}/usr/bin/h5debug
rm -f %{buildroot}/usr/bin/h5diff
rm -f %{buildroot}/usr/bin/h5dump
rm -f %{buildroot}/usr/bin/h5import
rm -f %{buildroot}/usr/bin/h5jam
rm -f %{buildroot}/usr/bin/h5ls
rm -f %{buildroot}/usr/bin/h5mkgrp
rm -f %{buildroot}/usr/bin/h5perf_serial
rm -f %{buildroot}/usr/bin/h5redeploy
rm -f %{buildroot}/usr/bin/h5repack
rm -f %{buildroot}/usr/bin/h5repart
rm -f %{buildroot}/usr/bin/h5stat
rm -f %{buildroot}/usr/bin/h5unjam
rm -f %{buildroot}/usr/include/H5ACpublic.h
rm -f %{buildroot}/usr/include/H5Apublic.h
rm -f %{buildroot}/usr/include/H5Cpublic.h
rm -f %{buildroot}/usr/include/H5DOpublic.h
rm -f %{buildroot}/usr/include/H5DSpublic.h
rm -f %{buildroot}/usr/include/H5Dpublic.h
rm -f %{buildroot}/usr/include/H5Epubgen.h
rm -f %{buildroot}/usr/include/H5Epublic.h
rm -f %{buildroot}/usr/include/H5FDcore.h
rm -f %{buildroot}/usr/include/H5FDdirect.h
rm -f %{buildroot}/usr/include/H5FDfamily.h
rm -f %{buildroot}/usr/include/H5FDlog.h
rm -f %{buildroot}/usr/include/H5FDmpi.h
rm -f %{buildroot}/usr/include/H5FDmpio.h
rm -f %{buildroot}/usr/include/H5FDmulti.h
rm -f %{buildroot}/usr/include/H5FDpublic.h
rm -f %{buildroot}/usr/include/H5FDsec2.h
rm -f %{buildroot}/usr/include/H5FDstdio.h
rm -f %{buildroot}/usr/include/H5Fpublic.h
rm -f %{buildroot}/usr/include/H5Gpublic.h
rm -f %{buildroot}/usr/include/H5IMpublic.h
rm -f %{buildroot}/usr/include/H5Ipublic.h
rm -f %{buildroot}/usr/include/H5LTpublic.h
rm -f %{buildroot}/usr/include/H5Lpublic.h
rm -f %{buildroot}/usr/include/H5MMpublic.h
rm -f %{buildroot}/usr/include/H5Opublic.h
rm -f %{buildroot}/usr/include/H5PLextern.h
rm -f %{buildroot}/usr/include/H5PLpublic.h
rm -f %{buildroot}/usr/include/H5PTpublic.h
rm -f %{buildroot}/usr/include/H5Ppublic.h
rm -f %{buildroot}/usr/include/H5Rpublic.h
rm -f %{buildroot}/usr/include/H5Spublic.h
rm -f %{buildroot}/usr/include/H5TBpublic.h
rm -f %{buildroot}/usr/include/H5Tpublic.h
rm -f %{buildroot}/usr/include/H5Zpublic.h
rm -f %{buildroot}/usr/include/H5api_adpt.h
rm -f %{buildroot}/usr/include/H5overflow.h
rm -f %{buildroot}/usr/include/H5pubconf.h
rm -f %{buildroot}/usr/include/H5public.h
rm -f %{buildroot}/usr/include/H5version.h
rm -f %{buildroot}/usr/include/hdf5.h
rm -f %{buildroot}/usr/include/hdf5_hl.h
rm -f %{buildroot}/usr/lib64/libhdf5.so
rm -f %{buildroot}/usr/lib64/libhdf5_hl.so
rm -f %{buildroot}/usr/share/hdf5_examples/README
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_attribute.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_chunk_read.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_cmprss.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_compound.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_crtatt.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_crtdat.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_crtgrp.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_crtgrpar.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_crtgrpd.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_drivers.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_elink_unix2win.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_extend.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_extend_write.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_extlink.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_group.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_mount.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_rdwt.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_read.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_ref2reg.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_reference.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_select.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_shared_mesg.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_subset.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/h5_write.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/ph5example.c
rm -f %{buildroot}/usr/share/hdf5_examples/c/run-c-ex.sh
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_ds1.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_image1.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_image2.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_lite1.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_lite2.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_lite3.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_01.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_02.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_03.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_04.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_05.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_06.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_07.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_08.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_09.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_10.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_11.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ex_table_12.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/image24pixel.txt
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/image8.txt
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/pal_rgb.h
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/ptExampleFL.c
rm -f %{buildroot}/usr/share/hdf5_examples/hl/c/run-hlc-ex.sh
rm -f %{buildroot}/usr/share/hdf5_examples/hl/run-hl-ex.sh
rm -f %{buildroot}/usr/share/hdf5_examples/run-all-ex.sh

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhdf5.so.10
/usr/lib64/libhdf5.so.10.3.1
/usr/lib64/libhdf5_hl.so.10
/usr/lib64/libhdf5_hl.so.10.2.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-hdf5-soname10/COPYING
