#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : compat-hdf5-soname10
Version  : 1.8.20
Release  : 3
URL      : https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.20.tar.gz
Source0  : https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.20.tar.gz
Summary  : HDF5 is a unique technology suite that makes possible the management of extremely large and complex data collections.
Group    : Development/Tools
License  : BSD-4-Clause-UC
Requires: compat-hdf5-soname10-bin
Requires: compat-hdf5-soname10-lib
Requires: compat-hdf5-soname10-license
Requires: compat-hdf5-soname10-data
BuildRequires : buildreq-cmake
BuildRequires : glibc-dev
BuildRequires : openmpi-dev
BuildRequires : pkgconfig(zlib)

%description
h5repack_nested_8bit_enum_deflated.h5:
h5repack_nested_8bit_enum.h5:
enuberated 8bit type nested in compount type.  Original file provided
by a user (HDFFV-8667) as a test file. Used h5copy to extract only the
Compound type dataset. The non-deflated version is produced by h5repack.

%package bin
Summary: bin components for the compat-hdf5-soname10 package.
Group: Binaries
Requires: compat-hdf5-soname10-data
Requires: compat-hdf5-soname10-license

%description bin
bin components for the compat-hdf5-soname10 package.


%package data
Summary: data components for the compat-hdf5-soname10 package.
Group: Data

%description data
data components for the compat-hdf5-soname10 package.


%package dev
Summary: dev components for the compat-hdf5-soname10 package.
Group: Development
Requires: compat-hdf5-soname10-lib
Requires: compat-hdf5-soname10-bin
Requires: compat-hdf5-soname10-data
Provides: compat-hdf5-soname10-devel

%description dev
dev components for the compat-hdf5-soname10 package.


%package lib
Summary: lib components for the compat-hdf5-soname10 package.
Group: Libraries
Requires: compat-hdf5-soname10-data
Requires: compat-hdf5-soname10-license

%description lib
lib components for the compat-hdf5-soname10 package.


%package license
Summary: license components for the compat-hdf5-soname10 package.
Group: Default

%description license
license components for the compat-hdf5-soname10 package.


%prep
%setup -q -n hdf5-1.8.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535766527
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1535766527
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/compat-hdf5-soname10
cp COPYING %{buildroot}/usr/share/doc/compat-hdf5-soname10/COPYING
%make_install

%files
%defattr(-,root,root,-)
%exclude /usr/lib64/libhdf5.settings

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/gif2h5
%exclude /usr/bin/h52gif
%exclude /usr/bin/h5cc
%exclude /usr/bin/h5copy
%exclude /usr/bin/h5debug
%exclude /usr/bin/h5diff
%exclude /usr/bin/h5dump
%exclude /usr/bin/h5import
%exclude /usr/bin/h5jam
%exclude /usr/bin/h5ls
%exclude /usr/bin/h5mkgrp
%exclude /usr/bin/h5perf_serial
%exclude /usr/bin/h5redeploy
%exclude /usr/bin/h5repack
%exclude /usr/bin/h5repart
%exclude /usr/bin/h5stat
%exclude /usr/bin/h5unjam

%files data
%defattr(-,root,root,-)
%exclude /usr/share/hdf5_examples/README
%exclude /usr/share/hdf5_examples/c/h5_attribute.c
%exclude /usr/share/hdf5_examples/c/h5_chunk_read.c
%exclude /usr/share/hdf5_examples/c/h5_cmprss.c
%exclude /usr/share/hdf5_examples/c/h5_compound.c
%exclude /usr/share/hdf5_examples/c/h5_crtatt.c
%exclude /usr/share/hdf5_examples/c/h5_crtdat.c
%exclude /usr/share/hdf5_examples/c/h5_crtgrp.c
%exclude /usr/share/hdf5_examples/c/h5_crtgrpar.c
%exclude /usr/share/hdf5_examples/c/h5_crtgrpd.c
%exclude /usr/share/hdf5_examples/c/h5_drivers.c
%exclude /usr/share/hdf5_examples/c/h5_elink_unix2win.c
%exclude /usr/share/hdf5_examples/c/h5_extend.c
%exclude /usr/share/hdf5_examples/c/h5_extend_write.c
%exclude /usr/share/hdf5_examples/c/h5_extlink.c
%exclude /usr/share/hdf5_examples/c/h5_group.c
%exclude /usr/share/hdf5_examples/c/h5_mount.c
%exclude /usr/share/hdf5_examples/c/h5_rdwt.c
%exclude /usr/share/hdf5_examples/c/h5_read.c
%exclude /usr/share/hdf5_examples/c/h5_ref2reg.c
%exclude /usr/share/hdf5_examples/c/h5_reference.c
%exclude /usr/share/hdf5_examples/c/h5_select.c
%exclude /usr/share/hdf5_examples/c/h5_shared_mesg.c
%exclude /usr/share/hdf5_examples/c/h5_subset.c
%exclude /usr/share/hdf5_examples/c/h5_write.c
%exclude /usr/share/hdf5_examples/c/ph5example.c
%exclude /usr/share/hdf5_examples/c/run-c-ex.sh
%exclude /usr/share/hdf5_examples/hl/c/ex_ds1.c
%exclude /usr/share/hdf5_examples/hl/c/ex_image1.c
%exclude /usr/share/hdf5_examples/hl/c/ex_image2.c
%exclude /usr/share/hdf5_examples/hl/c/ex_lite1.c
%exclude /usr/share/hdf5_examples/hl/c/ex_lite2.c
%exclude /usr/share/hdf5_examples/hl/c/ex_lite3.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_01.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_02.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_03.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_04.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_05.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_06.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_07.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_08.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_09.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_10.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_11.c
%exclude /usr/share/hdf5_examples/hl/c/ex_table_12.c
%exclude /usr/share/hdf5_examples/hl/c/image24pixel.txt
%exclude /usr/share/hdf5_examples/hl/c/image8.txt
%exclude /usr/share/hdf5_examples/hl/c/pal_rgb.h
%exclude /usr/share/hdf5_examples/hl/c/ptExampleFL.c
%exclude /usr/share/hdf5_examples/hl/c/run-hlc-ex.sh
%exclude /usr/share/hdf5_examples/hl/run-hl-ex.sh
%exclude /usr/share/hdf5_examples/run-all-ex.sh

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/H5ACpublic.h
%exclude /usr/include/H5Apublic.h
%exclude /usr/include/H5Cpublic.h
%exclude /usr/include/H5DOpublic.h
%exclude /usr/include/H5DSpublic.h
%exclude /usr/include/H5Dpublic.h
%exclude /usr/include/H5Epubgen.h
%exclude /usr/include/H5Epublic.h
%exclude /usr/include/H5FDcore.h
%exclude /usr/include/H5FDdirect.h
%exclude /usr/include/H5FDfamily.h
%exclude /usr/include/H5FDlog.h
%exclude /usr/include/H5FDmpi.h
%exclude /usr/include/H5FDmpio.h
%exclude /usr/include/H5FDmulti.h
%exclude /usr/include/H5FDpublic.h
%exclude /usr/include/H5FDsec2.h
%exclude /usr/include/H5FDstdio.h
%exclude /usr/include/H5Fpublic.h
%exclude /usr/include/H5Gpublic.h
%exclude /usr/include/H5IMpublic.h
%exclude /usr/include/H5Ipublic.h
%exclude /usr/include/H5LTpublic.h
%exclude /usr/include/H5Lpublic.h
%exclude /usr/include/H5MMpublic.h
%exclude /usr/include/H5Opublic.h
%exclude /usr/include/H5PLextern.h
%exclude /usr/include/H5PLpublic.h
%exclude /usr/include/H5PTpublic.h
%exclude /usr/include/H5Ppublic.h
%exclude /usr/include/H5Rpublic.h
%exclude /usr/include/H5Spublic.h
%exclude /usr/include/H5TBpublic.h
%exclude /usr/include/H5Tpublic.h
%exclude /usr/include/H5Zpublic.h
%exclude /usr/include/H5api_adpt.h
%exclude /usr/include/H5overflow.h
%exclude /usr/include/H5pubconf.h
%exclude /usr/include/H5public.h
%exclude /usr/include/H5version.h
%exclude /usr/include/hdf5.h
%exclude /usr/include/hdf5_hl.h
%exclude /usr/lib64/libhdf5.so
%exclude /usr/lib64/libhdf5_hl.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libhdf5.so.10
/usr/lib64/libhdf5.so.10.3.1
/usr/lib64/libhdf5_hl.so.10
/usr/lib64/libhdf5_hl.so.10.2.1

%files license
%defattr(-,root,root,-)
%exclude /usr/share/doc/compat-hdf5-soname10/COPYING
